In [1]:
import numpy as np
import pandas as pd

In [9]:
train_df = pd.read_csv('C:/notebooks/kaggle/train.csv', index_col=0)
test_df = pd.read_csv('C:/notebooks/kaggle/test.csv',index_col=0)

In [10]:
train_df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [13]:
test_df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [11]:
train_df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [12]:
print(train_df.shape)
print(test_df.shape)

(1460, 80)
(1459, 79)

In [14]:
y_train = train_df.pop('SalePrice') #extract lable from train_df

In [17]:
all_df = pd.concat((train_df, test_df), axis=0)

In [18]:
all_df.shape

(2919, 79)

In [19]:
all_df.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
Length: 79, dtype: object

In [22]:
data_MSSubClass = pd.get_dummies(all_df['MSSubClass'],prefix='MSSubClass')
pd.DataFrame(data_MSSubClass)

,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,MSSubClass_90,MSSubClass_120,MSSubClass_150,MSSubClass_160,MSSubClass_180,MSSubClass_190
Id,,,,,,,,,,,,,,,,
1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2916,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2917,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2918,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2919,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [40]:
all_dummy_df = pd.get_dummies(all_df)
all_dummy_df.drop('MSSubClass',axis=1,inplace=True)
all_dummy_df=pd.concat((all_dummy_df,data_MSSubClass), axis=1)
all_dummy_df

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,MSSubClass_90,MSSubClass_120,MSSubClass_150,MSSubClass_160,MSSubClass_180,MSSubClass_190
Id,,,,,,,,,,,,,,,,,,,,,
1,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,...,0,0,0,0,0,0,0,0,0,0
2,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,...,0,0,0,0,0,0,0,0,0,0
3,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,...,0,0,0,0,0,0,0,0,0,0
4,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,540.0,...,1,0,0,0,0,0,0,0,0,0
5,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,490.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,546.0,...,0,0,0,0,0,0,0,1,0,0
2916,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,294.0,...,0,0,0,0,0,0,0,1,0,0
2917,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2918,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,575.0,...,0,0,0,1,0,0,0,0,0,0
2919,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,238.0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
all_dummy_df.isnull().sum().sort_values(ascending=False).head(20)

LotFrontage              486
GarageYrBlt              159
MasVnrArea                23
BsmtFullBath               2
BsmtHalfBath               2
BsmtFinSF1                 1
BsmtFinSF2                 1
BsmtUnfSF                  1
TotalBsmtSF                1
GarageArea                 1
GarageCars                 1
Condition1_RRNe            0
Condition1_RRNn            0
Condition2_Artery          0
Condition1_RRAn            0
Condition2_Feedr           0
Condition2_Norm            0
SaleCondition_Partial      0
Condition2_PosA            0
Condition2_PosN            0
dtype: int64

In [41]:
all_dummy_df = all_dummy_df.fillna(method='ffill') #用上一個非nan的值補空值

In [44]:
all_dummy_df.isnull().sum().sort_values(ascending=False).head(20)

MSSubClass_190       0
Condition1_RRNe      0
Condition2_Artery    0
Condition2_Feedr     0
Condition2_Norm      0
Condition2_PosA      0
Condition2_PosN      0
Condition2_RRAe      0
Condition2_RRAn      0
Condition2_RRNn      0
BldgType_1Fam        0
BldgType_2fmCon      0
BldgType_Duplex      0
BldgType_Twnhs       0
BldgType_TwnhsE      0
HouseStyle_1.5Fin    0
HouseStyle_1.5Unf    0
Condition1_RRNn      0
Condition1_RRAn      0
HouseStyle_2.5Fin    0
dtype: int64

In [45]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [46]:
corr = all_dummy_df.astype(float).corr()
corr

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MSSubClass_70,MSSubClass_75,MSSubClass_80,MSSubClass_85,MSSubClass_90,MSSubClass_120,MSSubClass_150,MSSubClass_160,MSSubClass_180,MSSubClass_190
LotFrontage,1.000000,0.341828,0.183147,-0.066592,0.105684,0.066635,0.184023,0.184984,0.054818,0.092587,...,-0.046725,0.017057,0.062221,0.029338,0.009135,-0.246260,0.002079,-0.372373,-0.144051,-0.012109
LotArea,0.341828,1.000000,0.100541,-0.035617,0.024128,0.021612,0.124294,0.194149,0.084107,0.021388,...,-0.013124,0.010144,0.018671,-0.010064,-0.019805,-0.159257,-0.019880,-0.205317,-0.075813,0.054768
OverallQual,0.183147,0.100541,1.000000,-0.093847,0.597554,0.571532,0.430571,0.282087,-0.042605,0.275145,...,-0.024213,0.038346,-0.009267,-0.063586,-0.135493,0.203818,0.011962,-0.008784,-0.075098,-0.116264
OverallCond,-0.066592,-0.035617,-0.093847,1.000000,-0.368477,0.047654,-0.136062,-0.050760,0.041359,-0.138226,...,0.220584,0.073163,0.033415,0.048167,-0.099911,-0.107897,-0.009391,-0.056021,0.009718,0.001207
YearBuilt,0.105684,0.024128,0.597554,-0.368477,1.000000,0.612235,0.313826,0.279750,-0.027507,0.130498,...,-0.378355,-0.161224,0.032569,0.010583,-0.025898,0.233587,0.005310,0.101588,0.029833,-0.187501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSSubClass_120,-0.246260,-0.159257,0.203818,-0.107897,0.233587,0.182908,0.023647,0.107332,-0.004933,0.048857,...,-0.055223,-0.022981,-0.052928,-0.033343,-0.050788,1.000000,-0.004774,-0.055223,-0.019737,-0.037673
MSSubClass_150,0.002079,-0.019880,0.011962,-0.009391,0.005310,-0.002893,-0.010579,-0.001800,-0.005425,-0.022235,...,-0.003964,-0.001650,-0.003800,-0.002394,-0.003646,-0.004774,1.000000,-0.003964,-0.001417,-0.002705
MSSubClass_160,-0.372373,-0.205317,-0.008784,-0.056021,0.101588,0.025559,0.079180,-0.082825,-0.026610,-0.084371,...,-0.045862,-0.019085,-0.043955,-0.027690,-0.042178,-0.055223,-0.003964,1.000000,-0.016391,-0.031287
MSSubClass_180,-0.144051,-0.075813,-0.075098,0.009718,0.029833,0.010453,-0.031707,0.003855,0.003630,-0.089469,...,-0.016391,-0.006821,-0.015709,-0.009896,-0.015074,-0.019737,-0.001417,-0.016391,1.000000,-0.011182
MSSubClass_190,-0.012109,0.054768,-0.116264,0.001207,-0.187501,-0.105717,-0.069127,0.020164,-0.029089,-0.063341,...,-0.031287,-0.013020,-0.029986,-0.018890,-0.028774,-0.037673,-0.002705,-0.031287,-0.011182,1.000000

In [77]:
train_df.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460],
           dtype='int64', name='Id', length=1460)

In [83]:
dummy_train_df = all_dummy_df.loc[:1460]
dummy_test_df = all_dummy_df.loc[1461:]

In [84]:
dummy_train_df=pd.concat((dummy_train_df,y_train),axis=1)
dummy_train_df

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,MSSubClass_75,MSSubClass_80,MSSubClass_85,MSSubClass_90,MSSubClass_120,MSSubClass_150,MSSubClass_160,MSSubClass_180,MSSubClass_190,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,150.0,...,0,0,0,0,0,0,0,0,0,208500
2,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,284.0,...,0,0,0,0,0,0,0,0,0,181500
3,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,434.0,...,0,0,0,0,0,0,0,0,0,223500
4,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,540.0,...,0,0,0,0,0,0,0,0,0,140000
5,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,490.0,...,0,0,0,0,0,0,0,0,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,62.0,7917,6,5,1999,2000,0.0,0.0,0.0,953.0,...,0,0,0,0,0,0,0,0,0,175000
1457,85.0,13175,6,6,1978,1988,119.0,790.0,163.0,589.0,...,0,0,0,0,0,0,0,0,0,210000
1458,66.0,9042,7,9,1941,2006,0.0,275.0,0.0,877.0,...,0,0,0,0,0,0,0,0,0,266500
1459,68.0,9717,5,6,1950,1996,0.0,49.0,1029.0,0.0,...,0,0,0,0,0,0,0,0,0,142125
1460,75.0,9937,5,6,1965,1965,0.0,830.0,290.0,136.0,...,0,0,0,0,0,0,0,0,0,147500

In [123]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [124]:
X=dummy_train_df.drop('SalePrice',axis=1)
y=dummy_train_df.SalePrice

In [125]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [126]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.3,
                max_depth = 5, alpha = 10, n_estimators = 100)
xg_reg.fit(X_train,y_train)
y_preds = xg_reg.predict(X_test)

[14:21:02] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.
[14:21:02] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.

In [128]:
rmse = np.sqrt(mean_squared_error(y_test, y_preds))
print("RMSE: %f" % (rmse))
print('R2 score: {}'.format(r2_score(y_test, y_preds)))

RMSE: 24594.823591
R2 score: 0.9021127774289726

In [116]:
print(y_preds.shape)
print(y_test.shape)

(292,)
(292,)

In [132]:
xg_reg.fit(X_train, y_train, eval_metric='rmse', verbose = True, eval_set = [(X_test, y_test)],early_stopping_rounds=50)
preds = xg_reg.predict(X_test)

[14:25:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.
[0]	validation_0-rmse:144024.68750
Will train until validation_0-rmse hasn't improved in 50 rounds.
[1]	validation_0-rmse:106836.12500
[2]	validation_0-rmse:79870.85156
[3]	validation_0-rmse:62006.91797
[4]	validation_0-rmse:48988.61719
[5]	validation_0-rmse:41532.80078
[6]	validation_0-rmse:35989.27344
[7]	validation_0-rmse:32522.89453
[8]	validation_0-rmse:30178.71289
[9]	validation_0-rmse:28960.56836
[10]	validation_0-rmse:27726.81641
[11]	validation_0-rmse:27211.40430
[12]	validation_0-rmse:26405.32227
[13]	validation_0-rmse:26222.99414
[14]	validation_0-rmse:25982.18164
[15]	validation_0-rmse:26024.82617
[16]	validation_0-rmse:25801.68359
[17]	validation_0-rmse:25664.19531
[18]	validation_0-rmse:25487.56250
[19]	validation_0-rmse:25402.45898
[20]	validation_0-rmse:25202.97461
[21]	validation_0-rmse:25245.74805
[22]	validation_0-rmse:25228.71680
[23]	validation_0-rmse:25067.68359
[24]	validation_0-rmse:25014.93359
[25]	validation_0-rmse:24910.97461
[26]	validation_0-rmse:24838.24414
[27]	validation_0-rmse:24777.17578
[28]	validation_0-rmse:24738.46875
[29]	validation_0-rmse:24801.04883
[30]	validation_0-rmse:24846.69727
[31]	validation_0-rmse:24846.24609
[32]	validation_0-rmse:24703.71289
[33]	validation_0-rmse:24702.80273
[34]	validation_0-rmse:24722.85742
[35]	validation_0-rmse:24790.54883
[36]	validation_0-rmse:24791.62109
[37]	validation_0-rmse:24760.67773
[38]	validation_0-rmse:24722.51172
[39]	validation_0-rmse:24738.22852
[40]	validation_0-rmse:24795.94531
[41]	validation_0-rmse:24776.76758
[42]	validation_0-rmse:24728.01758
[43]	validation_0-rmse:24755.14062
[44]	validation_0-rmse:24752.17969
[45]	validation_0-rmse:24717.55078
[46]	validation_0-rmse:24720.65234
[47]	validation_0-rmse:24677.85742
[48]	validation_0-rmse:24728.72266
[49]	validation_0-rmse:24665.09375
[50]	validation_0-rmse:24723.89258
[51]	validation_0-rmse:24735.90820
[52]	validation_0-rmse:24651.61523
[53]	validation_0-rmse:24613.09570
[54]	validation_0-rmse:24650.75391
[55]	validation_0-rmse:24643.52734
[56]	validation_0-rmse:24641.54688
[57]	validation_0-rmse:24703.60156
[58]	validation_0-rmse:24723.34961
[59]	validation_0-rmse:24729.22070
[60]	validation_0-rmse:24712.27539
[61]	validation_0-rmse:24705.35938
[62]	validation_0-rmse:24676.62500
[63]	validation_0-rmse:24684.23438
[64]	validation_0-rmse:24694.89648
[65]	validation_0-rmse:24702.44727
[66]	validation_0-rmse:24671.61133
[67]	validation_0-rmse:24679.57812
[68]	validation_0-rmse:24655.19141
[69]	validation_0-rmse:24600.24609
[70]	validation_0-rmse:24595.95898
[71]	validation_0-rmse:24621.67188
[72]	validation_0-rmse:24581.69922
[73]	validation_0-rmse:24598.41992
[74]	validation_0-rmse:24582.87305
[75]	validation_0-rmse:24591.11719
[76]	validation_0-rmse:24578.30273
[77]	validation_0-rmse:24621.94336
[78]	validation_0-rmse:24627.85352
[79]	validation_0-rmse:24629.50391
[80]	validation_0-rmse:24645.95312
[81]	validation_0-rmse:24655.67383
[82]	validation_0-rmse:24627.85156
[83]	validation_0-rmse:24645.38672
[84]	validation_0-rmse:24646.13867
[85]	validation_0-rmse:24643.95117
[86]	validation_0-rmse:24647.65234
[87]	validation_0-rmse:24613.75586
[88]	validation_0-rmse:24591.57227
[89]	validation_0-rmse:24600.94141
[90]	validation_0-rmse:24604.56250
[91]	validation_0-rmse:24587.74219
[92]	validation_0-rmse:24589.52539
[93]	validation_0-rmse:24587.64062
[94]	validation_0-rmse:24584.01758
[95]	validation_0-rmse:24587.24805
[96]	validation_0-rmse:24583.97656
[97]	validation_0-rmse:24592.12695
[98]	validation_0-rmse:24591.03125
[99]	validation_0-rmse:24594.82422
[14:25:08] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.

In [134]:
from joblib import dump, load
dump(xg_reg, 'XGBRegressor.joblib')

['XGBRegressor.joblib']

In [136]:
test_model = load('XGBRegressor.joblib')

[14:35:03] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.2.0/src/objective/regression_obj.cu:174: reg:linear is now deprecated in favor of reg:squarederror.

In [140]:
test_preds=test_model.predict(dummy_test_df)
test_preds

array([131860.72, 162183.53, 179050.44, ..., 155437.94, 111720.79,
       201938.75], dtype=float32)

In [141]:
submission_df = pd.DataFrame(data= {'Id' : test_df.index, 'SalePrice': test_preds})

In [142]:
submission_df

        Id      SalePrice
0     1461  131860.718750
1     1462  162183.531250
2     1463  179050.437500
3     1464  189195.484375
4     1465  171876.421875
...    ...            ...
1454  2915   84437.460938
1455  2916   80144.179688
1456  2917  155437.937500
1457  2918  111720.789062
1458  2919  201938.750000

[1459 rows x 2 columns]